name: TheBean
options:
  generateEmptyDirectories: true
  bundleIdPrefix: ${BUNDLE_ID_PREFIX}
  deploymentTarget:
    iOS: 13.0
targets:
  TheBean:
    type: application
    platform: iOS
    sources: 
      - path: TheBean
    settings:
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    info:
      path: TheBean/Resources/Info.plist
      properties:
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: ${BUNDLE_ID_PREFIX}.TheBean
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        UIAppFonts:
          - AssetsManagerResources.bundle/MullerLight.ttf
          - AssetsManagerResources.bundle/MullerRegular.ttf
          - AssetsManagerResources.bundle/MullerMedium.ttf
          - AssetsManagerResources.bundle/MullerBold.ttf
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              -
                UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations: []
    postCompileScripts:
      - script: |
          if [ -z "$CI" ]; then
          ${PODS_ROOT}/SwiftLint/swiftlint --fix
          fi
        name: SwiftlintFix
      - script: |
          if [ -z "$CI" ]; then
          ${PODS_ROOT}/SwiftLint/swiftlint
          fi
        name: Swiftlint