name: CI
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  setup:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Xcodegen
        run: |
          ls
          brew upgrade xcodegen || brew install xcodegen
          xcodegen
          ls
      - name: CocoaPod Install
        run: pod install
      - name: Run linter
        run: |
          pwd
          ls -la
          echo here
          swiftlint --fix
          swiftlint
      - name: Build
        run: ls
  linter:
    runs-on: macOS-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          pwd
          ls -la
          echo here
          swiftlint --fix
          swiftlint
  build:
    runs-on: macOS-latest
    needs:
      - setup
      - linter
    uses: actions/cache@v2
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          ls
          xcodebuild -scheme "TheBean" -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' -workspace TheBean.xcworkspace -quiet