name: CI
on:
  pull_request:
    branches:
      - main
      - dev
      - CI
  push:
    branches:
      - main
      - dev
      - CI

jobs:
  Install:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Xcodegen
        run: |
          brew upgrade xcodegen || brew install xcodegen
          xcodegen

      - name: CocoaPod Install
        run: pod install
        
  Lint:
    runs-on: macOS-latest
    needs: Install

    steps:
      - name: Linter
        run: |
          swiftlint --fix
          swiftlint
  Build:
    runs-on: macOS-latest
    needs: Lint
    steps:
      - name: Build
        run: |
          ls
          xcodebuild -scheme "TheBean" -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' -workspace TheBean.xcworkspace -quiet