name: CI
on:
  pull_request:
    branches:
      - main
      - dev
      - TIC-CI
  push:
    branches:
      - main
      - dev
      - TIC-CI

jobs:

  Preinstall:
    runs-on: macOS-latest
    steps:
    - name: Update Homebrew
      run: |
        brew update --preinstall
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/xcodegen.rb" > .github/brew-formulae
    - name: Configure Homebrew cache
      uses: actions/cache@v1
      with:
        path: |
          ~/Library/Caches/Homebrew/xcodegen--*
          ~/Library/Caches/Homebrew/downloads/*--xcodegen-*
        key: brew-${{ hashFiles('.github/brew-formulae') }}
        restore-keys: brew-
    - name: Install Homebrew dependencies
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install xcodegen

  Install:
    runs-on: macOS-latest
    needs: Preinstall

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.os }}-cache-${{ github.run_id }}

      - name: Xcodegen
        run: |
          brew upgrade xcodegen || brew install xcodegen
          xcodegen
          ls -la

      - name: CocoaPod Install
        run: |
          pod install
          ls -la
        
  Lint:
    runs-on: macOS-latest
    needs: Install

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.os }}-cache-${{ github.run_id }}
      - name: Linter
        run: |
          ls -la
  Build:
    runs-on: macOS-latest
    needs: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.os }}-cache-${{ github.run_id }}
      - name: Build
        run: |
          ls -la
          xcodebuild -scheme "TheBean" -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' -workspace TheBean.xcworkspace -quiet