name: CI
on:
  pull_request:
    branches:
      - main
      - dev
      - TIC-CI
  push:
    branches:
      - main
      - dev
      - TIC-CI

jobs:

  Preinstall:
    runs-on: macOS-latest

    steps:
    - name: Cache
        uses: actions/cache@v1
        with:
          path: /usr/local/Cellar/xcodegen/
          key: ${{ runner.os }}-cache-xcodegen
    - name: Xcodegen
      run: |
        brew install xcodegen

  Install:
    runs-on: macOS-latest
    needs: Preinstall

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.os }}-cache-${{ github.run_id }}

      - name: Xcodegen
        run: |
          xcodegen

      - name: CocoaPod Install
        run: |
          pod install
        
  Lint:
    runs-on: macOS-latest
    needs: Install

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.os }}-cache-${{ github.run_id }}
      - name: Linter
        run: |
          swiftlint --fix
          swiftlint

  Build:
    runs-on: macOS-latest
    needs: Lint

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ./
          key: ${{ runner.os }}-cache-${{ github.run_id }}
      - name: Build
        run: |
          xcodebuild -scheme "TheBean" -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' -workspace TheBean.xcworkspace -quiet