name: CI
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  setup:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  linter:
    needs:
      - setup
    runs-on: macOS-latest
    steps:
      - name: Run linter
        run: |
          swiftlint --fix
          swiftlint
  build:
    needs:
      - setup
      - linter
    runs-on: macOS-latest
    steps:
      - name: Xcodegen
        run: |
          brew upgrade xcodegen || brew install xcodegen
          xcodegen
      - name: Build
        run: xcodebuild -scheme "TheBean" -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' -workspace TheBean.xcworkspace -quiet