name: CI
on:
  pull_request:
    branches:
      - main
      - dev
      - TIC-CI
  push:
    branches:
      - main
      - dev
      - TIC-CI

jobs:
  Install:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Xcodegen
        run: |
          brew upgrade xcodegen || brew install xcodegen
          xcodegen
          ls -la

      - name: CocoaPod Install
        run: |
          pod install
          ls -la
        
  Lint:
    runs-on: macOS-latest
    needs: Install

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      - name: Linter
        run: |
          ls -la
  Build:
    runs-on: macOS-latest
    needs: Lint
    steps:
      - uses: actions/cache@v1
      - name: Build
        run: |
          ls -la